f = open("foo.txt","w")
num = f.write("超哥最帅！\n嗯，确实帅！\n")
print(num)
f.close()
f = open("foo.txt","a+")
f.write("php是世界上最好的语言！\n")
f.close()
f = open("foo.txt","r")
#str = f.readline()
print(f.readline())
print(f.readline())
print(f.readline())
f.close()
f = open("foo.txt","r+")
print(f.seek(2))
print(f.read(1))
print(f.seek(4))
print(f.read(1))
f.close()
